version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  tts-server:
    build:
      context: .
      dockerfile: tts_server/Dockerfile
    volumes:
      - ./tts_server:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TTS_SERVER_PORT=5500
    ports:
      - "5500:5500"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  redis_data:
