services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  chat_reader:
    build: .
    command: python chat_reader_bot.py
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  podcaster:
    build: .
    command: python podcaster.py
    volumes:
      - .:/app
    depends_on:
      - redis
      - tts
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - TTS_HOST=tts

  tts:
    build:
      context: .
      dockerfile: tts_server/Dockerfile
    volumes:
      - ./tts_server:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TTS_SERVER_PORT=5500
    ports:
      - "5500:5500"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

networks:
  default:
    driver: bridge